### ISSUE TITLE
not enough logs

### ISSUE THREAD

**Issue by yegor256** [objectionary/ineo-maven-plugin#30]
I'm getting this:

```
[INFO] --- ineo:0.1.1:fuse (default-cli) @ benchmark ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

This is definitely not enough. Would be great to see where the files are taken, where expected to be stored, how many files were generated. See https://github.com/objectionary/jeo-maven-plugin/issues/373 for an example.

**Comment by yegor256** [comment]
@maxonfjvipon please, help

**Comment by maxonfjvipon** [comment]
@yegor256 tried to fix in https://github.com/objectionary/ineo-maven-plugin/pull/33. Please check if logs are sufficient for you now

**Comment by yegor256** [comment]
@maxonfjvipon yes, looks very good now! can you please release a new version, I will try in the benchmark project?

**Comment by maxonfjvipon** [comment]
@rultor release, tag is `0.1.2`

**Comment by yegor256** [comment]
@maxonfjvipon I don't see it here: https://repo1.maven.org/maven2/org/eolang/ineo-maven-plugin/

**Comment by yegor256** [comment]
@maxonfjvipon thanks!
