### ISSUE TITLE
FuseMojo.sourcesDir is defined too globally

### ISSUE THREAD

**Issue by yegor256** [objectionary/ineo-maven-plugin#32]
This is wrong: https://github.com/objectionary/ineo-maven-plugin/blob/master/src/main/java/org/eolang/ineo/FuseMojo.java#L77

Instead of `${basedir}` we should use `${project.build.outputDirectory}`, because `basedir` is not configurable from the outside, while the `outputDirectory` is configured through `pom.xml`.

**Comment by yegor256** [comment]
@maxonfjvipon because of this bug, we have this error: https://github.com/objectionary/benchmark/actions/runs/7322657817/job/19944413128 Please, fix asap

**Comment by maxonfjvipon** [comment]
@yegor256 tried to fixed in https://github.com/objectionary/ineo-maven-plugin/pull/33. Please check again

**Comment by yegor256** [comment]
@maxonfjvipon thanks!
