### ISSUE TITLE
site is not published

### ISSUE THREAD

**Issue by yegor256** [objectionary/ineo-maven-plugin#34]
Let's publish Maven site, similar to how it works for https://www.objectionary.com/jeo-maven-plugin/

See https://github.com/objectionary/jeo-maven-plugin/pull/358

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#47](https://github.com/objectionary/ineo-maven-plugin/issues/47) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#47](https://github.com/objectionary/ineo-maven-plugin/issues/47) is solved here.
