### ISSUE TITLE
site.xml:45-48: For some reason, the "plugin-info.html"...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/ineo-maven-plugin#47]
The puzzle `34-f1fb7c4b` from #34 has to be resolved: 

https://github.com/objectionary/ineo-maven-plugin/blob/d315a8524bf1e538b265205bc1542d7a2983ebc9/src/site/site.xml#L45-L48

The puzzle was created by @maxonfjvipon on 19-Jan-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@maxonfjvipon this one is fixed, just remove the puzzle and that's it

**Comment by 0pdd** [comment]
The puzzle `34-f1fb7c4b` has disappeared from the source code, that's why I closed this issue.
