### ISSUE TITLE
change default package to org.eolang.benchmark

### ISSUE THREAD

**Issue by yegor256** [objectionary/ineo-maven-plugin#50]
Currently it's [`com.example`](https://github.com/objectionary/ineo-maven-plugin/blob/d315a8524bf1e538b265205bc1542d7a2983ebc9/src/main/resources/org/eolang/ineo/fuse/BA.xmir#L15). Let's change it everywhere to `org.eolang.benchmark.`

**Comment by volodya-lombrozo** [comment]
Please, pay attention, that generated package `com.exam.BA` not `com.example.BA`. Which is rather strange and I don't understand where we are loosing `ple` suffix. It might be a bug in any of the plugins, but I would suggest to test it here first.
You can find more info here: https://github.com/objectionary/jeo-maven-plugin/issues/426

**Comment by maxonfjvipon** [comment]
@yegor256 could you please provide me a log of full pipeline?

**Comment by yegor256** [comment]
@maxonfjvipon this is the latest: https://github.com/objectionary/benchmark/actions/runs/7599780231/job/20697194996

**Comment by yegor256** [comment]
@maxonfjvipon please, check this one too: https://github.com/objectionary/jeo-maven-plugin/pull/430#issuecomment-1903897534

**Comment by maxonfjvipon** [comment]
@rultor release, tag is `0.1.4`

**Comment by maxonfjvipon** [comment]
@yegor256 please update `ineo-maven-plugin` to `0.1.4` and try again

**Comment by yegor256** [comment]
@maxonfjvipon apparently, the problem is still there: https://github.com/objectionary/benchmark/actions/runs/7612155714/job/20729140427 (the string `com.exam.BA` is still visible in the log)

**Comment by maxonfjvipon** [comment]
@yegor256 please update `ineo-maven-plugin` to `0.1.5` and try again

**Comment by maxonfjvipon** [comment]
@rultor release, tag is `0.1.5`

**Comment by maxonfjvipon** [comment]
@rultor release, tag is `0.1.6`

**Comment by maxonfjvipon** [comment]
@yegor256 update `ineo-maven-plugin` to `0.1.6` and try again

**Comment by maxonfjvipon** [comment]
@rultor release, tag is `0.1.6`

**Comment by maxonfjvipon** [comment]
@rultor release, tag is `0.1.7`
